name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3
  - matplotlib=3.5.3
  - pandas=2.2.3
  - pip=25.1.1
  - scikit-learn=1.6.1
  - jupyterlab=4.4.2
  - ipywidgets=8.1.7
  - jupyterlab_widgets=3.0.15
  - pip:
      - mlflow==2.21.0
      - wandb==0.19.11
      - ydata-profiling==4.3.0