name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.3
  - pytest=7.4.4
  - scipy=1.11.4
  - pip=24.0
  - pip:
      - mlflow==2.21.0
      - wandb==0.19.11
